"""``modules.Uui.widgets.settings_nav`` — Settings navigation tree component.

Renders based on :class:`TreeCanvas`; itself only responsible for "splitting SettingsSchema into
``scope -> group -> leaf`` three layers and feeding to TreeCanvas", as well as
reverse looking up TreeCanvas's iid into :class:`NavSelection` for upper layer consumption.

Public API is fully consistent with ttk.Treeview era:

* :meth:`set_roots` —— Rebuild entire tree with two schemas;
* :meth:`set_selected` —— Programmatic jump to specified scope/group/leaf;
* :meth:`get_selected` —— Currently selected :class:`NavSelection`;
* :meth:`set_on_select` / :meth:`set_title` —— Change callback/title at runtime;
* :meth:`_apply_theme` —— On theme switch, triggered recursively by
  :func:`modules.Uui.widgets.theme.apply_theme_recursive`.

Module-level pure functions (:func:`group_key` / :func:`node_id` /
:func:`parse_node_id` / :func:`group_keys_for_schema`) intentionally don't depend on
Tk, to allow unit testing in non-GUI environment (see ``tests/settings/test_settings_nav.py``).
"""

from __future__ import annotations

import contextlib
import tkinter as tk
from collections import OrderedDict
from collections.abc import Callable
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

from . import theme
from .frame import UFrame
from .label import ULabel
from .tree_canvas import TreeCanvas

if TYPE_CHECKING:
    from modules.settings.base import SettingsSchema


# --------------------------------------------------------------------------
# Pure data layer (no Tk dependency, independently testable)
# --------------------------------------------------------------------------


def group_key(spec_key: str) -> str:
    """Auto-group by ``key`` prefix.

    ``"editor.tab_size"`` -> ``"editor"``; no prefix (``"foo"``) -> ``"_"``.
    Consistent with ``_group_key`` behavior in :mod:`modules.settings.widgets`.
    """

    if "." in spec_key:
        return spec_key.split(".", 1)[0]
    return "_"


def node_id(scope_value: str, group_key: str | None = None, key: str | None = None) -> str:
    """Generate stable iid.

    * ``node_id("global")`` -> ``"global"``  (scope root)
    * ``node_id("global", "ui")`` -> ``"global:ui"``  (group)
    * ``node_id("global", "ui", "ui.theme")`` -> ``"global:ui:ui.theme"``  (leaf)
    """

    if key is not None:
        return f"{scope_value}:{group_key}:{key}"
    if group_key is not None:
        return f"{scope_value}:{group_key}"
    return scope_value


def parse_node_id(iid: str) -> tuple[str, str | None, str | None]:
    """Reverse parse result generated by :func:`node_id`.

    Returns ``(scope_value, group_key, key)``; any intermediate segment being ``None`` indicates
    that level doesn't exist (e.g., scope root has no group/key).
    """

    head, sep, rest = iid.partition(":")
    if not sep:
        return (head, None, None)
    group, sep2, key = rest.partition(":")
    if not sep2:
        return (head, group, None)
    return (head, group, key)


def group_keys_for_schema(schema: SettingsSchema) -> OrderedDict[str, list[tuple[str, str]]]:
    """Split one schema into ``{group_key: [(key, label), ...]}``.

    * Both groups and in-group specs preserve schema declaration order (using ``OrderedDict``),
      so tree rendered visual order is consistent with order in schema file, won't jump due to
      dictionary rehash.
    * Specs without group prefix go to ``"_"`` bucket.
    """

    groups: OrderedDict[str, list[tuple[str, str]]] = OrderedDict()
    for spec in schema:
        g = group_key(spec.key)
        groups.setdefault(g, []).append((spec.key, spec.label or spec.key))
    return groups


# --------------------------------------------------------------------------
# Selection event payload
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class NavSelection:
    """Payload passed back to listener when navigation tree node is selected.

    Fields:
        * ``scope`` —— Scope (GLOBAL / PROJECT).
        * ``group_key`` —— Node's group, ``None`` means scope root was clicked.
        * ``keys`` —— List of setting keys associated with node; scope root is empty,
          group node is empty (filtered by upper layer with ``filter_group_keys``),
          leaf node is single element.
        * ``label`` —— Node display text, for logging/debugging.
    """

    scope: Any  # modules.settings.base.SettingsScope (lazy load)
    group_key: str | None = None
    keys: tuple[str, ...] = field(default_factory=tuple)
    label: str = ""


# --------------------------------------------------------------------------
# Component main body
# --------------------------------------------------------------------------


class USettingsNavBar(UFrame):
    """Settings navigation tree: title header + Canvas tree + vertical Scrollbar.

    Typical usage (with :class:`UProjectSettingsWindow`)::

        nav = USettingsNavBar(
            parent,
            on_select=lambda sel: window.show_panel_for(sel),
        )
        nav.pack(side=tk.LEFT, fill=tk.Y)
        nav.set_roots(
            global_schema=settings_manager.global_settings.schema,
            project_schema=(
                settings_manager.project_settings.schema
                if settings_manager.project_settings else None
            ),
        )

    Parameters:
        parent -- Parent container.
        title -- Top title text, defaults to ``"Settings"``.
        on_select -- Callback when node is clicked / keyboard Enter triggers,
            receives one :class:`NavSelection`. Optional.
    """

    def __init__(
        self,
        parent,
        *,
        title: str = "Settings",
        on_select: Callable[[NavSelection], None] | None = None,
        scope_label_global: str = "Global",
        scope_label_project: str = "Project",
        **kwargs,
    ) -> None:
        # Visually consistent with file_tree: self is 'panel' container.
        kwargs.setdefault("variant", "panel")
        super().__init__(parent, **kwargs)

        self._on_select = on_select
        self._title_text = title
        self._scope_label_global = scope_label_global
        self._scope_label_project = scope_label_project

        # iid -> NavSelection, reset by set_roots.
        self._node_data: dict[str, NavSelection] = {}

        # Lazy load SettingsScope enum; fallback to string on failure to ensure component can still
        # construct (e.g., in demo scenario detached from settings subsystem).
        try:
            from modules.settings.base import SettingsScope

            self._SettingsScope = SettingsScope
        except Exception:  # pragma: no cover - defensive fallback
            self._SettingsScope = None

        self._build()

    # ------------------------------------------------------------------
    # Construction
    # ------------------------------------------------------------------

    def _build(self) -> None:
        # Title header: completely isomorphic with UFileTree (variant='title' + 26px height).
        header = UFrame(self, variant="title", height=26)
        header.pack(fill=tk.X)
        header.pack_propagate(False)
        self._title_label = ULabel(
            header,
            text=f"  {self._title_text}",
            variant="secondary",
            bg=theme.BG_TITLE,
        )
        self._title_label.pack(side=tk.LEFT, fill=tk.X, expand=True)

        self._tree = TreeCanvas(
            self,
            row_text=self._row_label,
            on_select=self._on_tree_select,
            on_activate=self._on_tree_activate,
        )
        self._tree.pack(fill=tk.BOTH, expand=True)

    def _row_label(self, iid: str) -> str:
        sel = self._node_data.get(iid)
        return sel.label if sel is not None else ""

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def set_on_select(
        self,
        callback: Callable[[NavSelection], None] | None,
    ) -> None:
        self._on_select = callback

    def set_title(self, text: str) -> None:
        self._title_text = text
        self._title_label.config(text=f"  {text}")

    def set_roots(
        self,
        global_schema: SettingsSchema | None,
        project_schema: SettingsSchema | None,
    ) -> NavSelection | None:
        """Rebuild entire tree with two schemas and auto-select first leaf.

        Returns the auto-selected :class:`NavSelection`; if both schemas are empty
        returns ``None``.
        """

        self._tree.clear()
        self._node_data.clear()

        first_leaf_iid: str | None = None

        if global_schema is not None:
            leaf_iid = self._populate_scope(
                self._SettingsScope.GLOBAL if self._SettingsScope else "global",
                global_schema,
                label=self._scope_label_global,
            )
            if first_leaf_iid is None:
                first_leaf_iid = leaf_iid

        if project_schema is not None:
            leaf_iid = self._populate_scope(
                self._SettingsScope.PROJECT if self._SettingsScope else "project",
                project_schema,
                label=self._scope_label_project,
            )
            if first_leaf_iid is None:
                first_leaf_iid = leaf_iid

        if first_leaf_iid is not None:
            self._tree.set_selected(first_leaf_iid, fire=False)
        return self._node_data.get(first_leaf_iid) if first_leaf_iid else None

    def set_selected(
        self,
        scope: Any,
        group_key: str | None = None,
        key: str | None = None,
    ) -> None:
        """Programmatic selection: all three depths of scope root / group / leaf are supported."""

        scope_value = getattr(scope, "value", str(scope))
        iid = node_id(scope_value, group_key, key)
        if self._tree.exists(iid):
            self._tree.set_selected(iid, fire=False)

    def get_selected(self) -> NavSelection | None:
        iid = self._tree.get_selected()
        if iid is None:
            return None
        return self._node_data.get(iid)

    # ------------------------------------------------------------------
    # Internal: populate tree
    # ------------------------------------------------------------------

    def _populate_scope(
        self,
        scope: Any,
        schema: SettingsSchema,
        *,
        label: str,
    ) -> str | None:
        """Insert ``scope -> group -> leaf`` three layers, return first leaf's iid."""

        scope_value = getattr(scope, "value", str(scope))
        scope_iid = node_id(scope_value)

        sel = NavSelection(
            scope=scope,
            group_key=None,
            keys=(),
            label=label,
        )
        self._node_data[scope_iid] = sel
        # Scope root expanded; TreeCanvas's add_node seeing is_open=True will
        # immediately render child nodes in _relayout.
        self._tree.add_node(scope_iid, None, is_open=True, data=sel)

        first_leaf_iid: str | None = None
        for g, items in group_keys_for_schema(schema).items():
            group_iid = node_id(scope_value, g)
            g_sel = NavSelection(
                scope=scope,
                group_key=g,
                keys=(),
                label=g,
            )
            self._node_data[group_iid] = g_sel
            # Group nodes also expanded: user clicking group can directly see leaves inside.
            self._tree.add_node(group_iid, scope_iid, is_open=True, data=g_sel)
            for spec_key, spec_label in items:
                leaf_iid = node_id(scope_value, g, spec_key)
                leaf_sel = NavSelection(
                    scope=scope,
                    group_key=g,
                    keys=(spec_key,),
                    label=spec_label,
                )
                self._node_data[leaf_iid] = leaf_sel
                self._tree.add_node(leaf_iid, group_iid, data=leaf_sel)
                if first_leaf_iid is None:
                    first_leaf_iid = leaf_iid
        return first_leaf_iid

    # ------------------------------------------------------------------
    # Internal: events
    # ------------------------------------------------------------------

    def _on_tree_select(self, iid: str) -> None:
        sel = self._node_data.get(iid)
        if sel is None or self._on_select is None:
            return
        with contextlib.suppress(Exception):
            self._on_select(sel)

    def _on_tree_activate(self, iid: str) -> None:
        # Consistent with original ttk.Treeview version: Enter / double-click both trigger on_select,
        # let panel switch to corresponding group or leaf.
        self._on_tree_select(iid)

    # ------------------------------------------------------------------
    # Theme
    # ------------------------------------------------------------------

    def _apply_theme(self) -> None:
        """Called by :func:`theme.apply_theme_recursive`, refresh all colors."""

        with contextlib.suppress(tk.TclError):
            super()._apply_theme()
        with contextlib.suppress(tk.TclError, AttributeError):
            self._title_label.config(
                bg=theme.BG_TITLE,
                fg=theme.FG_SECONDARY,
            )
        if hasattr(self._tree, "_apply_theme"):
            with contextlib.suppress(tk.TclError):
                self._tree._apply_theme()


__all__ = [
    "NavSelection",
    "USettingsNavBar",
    "group_key",
    "group_keys_for_schema",
    "node_id",
    "parse_node_id",
]
