# -*- mode: python ; coding: utf-8 -*-

from PyInstaller.utils.hooks import collect_data_files, collect_submodules

hiddenimports = [
    'modules.i18n',
    'modules.i18n.translator',
    'modules.settings',
    'modules.settings.base',
    'modules.settings.global_settings',
    'modules.settings.project_settings',
    'modules.settings.manager',
    'modules.settings.schema',
    'modules.settings.storage',
    'modules.settings.widgets',
    'modules.plugins',
    'modules.plugins.manager',
    'modules.plugins.api',
    'modules.plugins.hooks',
    'modules.plugins.widgets',
    'modules.highlighter',
    'modules.highlighter.base',
    'modules.highlighter.python',
    'modules.highlighter.ccpp',
    'modules.suggestion',
    'modules.suggestion.base',
    'modules.suggestion.python',
    'modules.suggestion.c',
    'modules.suggestion.cpp',
    'modules.checker',
    'modules.checker.base',
    'modules.checker.python',
    'modules.runner',
    'modules.Uui',
    'modules.Uui.widgets',
    'modules.Uui.widgets.window',
    'modules.Uui.widgets.theme',
    'modules.Uui.widgets.text',
    'modules.Uui.widgets.editor_suggestion',
    'modules.Uui.widgets.file_tree',
    'modules.Uui.widgets.line_number',
    'modules.Uui.widgets.scrollbar',
    'modules.Uui.widgets.slider',
    'modules.Uui.widgets.combobox',
    'modules.Uui.widgets.menu',
    'modules.Uui.widgets.frame',
    'modules.Uui.widgets.label',
    'modules.Uui.widgets.button',
    'modules.Uui.widgets.entry',
    'modules.Uui.widgets.checkbutton',
    'modules.Uui.widgets.radiobutton',
    'modules.Uui.widgets.progressbar',
    'modules.Uui.widgets.settings_nav',
    'modules.Uui.widgets.tree_canvas',
    'modules.Uui.call',
    'modules.Uui.call.pip',
    'modules.Uui.call.npm',
    'modules.Uui.call.git',
    'modules.Uui.web',
    'modules.Uui.web.app',
    'modules.Uui.web.cli',
    'modules.Uui.tool',
    'modules.Uui.tool.designer',
    'modules.Uui.demo',
    'json',
    'queue',
    'tkinter',
    'tkinter.ttk',
    'tkinter.filedialog',
    'tkinter.messagebox',
    'tkinter.simpledialog',
]

datas = [
    ('data/i18n/locales', 'modules/i18n/locales'),
]

binaries = []

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='PythonEditor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
